pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                checkout scm
            }
        }

        stage('Install & Test') {
            steps {
                dir('Devops') {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Devops') {
                    sh 'docker build -t devops-app .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                    docker rm -f devops-app || true
                    docker run -d --name devops-app -p 2000:2000 devops-app
                '''
            }
        }
    }
}