pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-app .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                    docker rm -f devops-app || true
                    docker run -d --name devops-app -p 3000:3000 devops-app
                '''
            }
        }
    }
}