services:
  - type: web
    name: taskflow-app
    runtime: node
    plan: free
    branch: main
    buildCommand: cd Devops && npm install && cd frontend && npm install --include=dev && npm run build
    startCommand: node Devops/backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 2000
      - key: DB_SSL
        value: true
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
